/**
 * Container-side allowlist seed. Inserts SEED_GITHUB_LOGIN into
 * `allowed_users` if not already present. No-op when the env var is
 * unset or empty. Runs from the container entrypoint after migrations
 * and before orphan-job recovery.
 *
 * Pure CommonJS, depends only on `pg`. Mirrors `scripts/recover-jobs.cjs`:
 * the runtime image only ships `/app/drizzle` and `/app/scripts`, not
 * `src/lib/db/schema`, so this file does NOT import the Drizzle schema
 * (the local-dev `scripts/db-seed.ts` does, via tsx). Slight duplication
 * accepted in exchange for not dragging the schema or `tsx` into the
 * runtime image.
 *
 * The `id` column on `allowed_users` is generated by Drizzle's
 * `$defaultFn(() => crypto.randomUUID())` at the application layer, NOT
 * by a database default. Raw SQL must supply it explicitly;
 * `gen_random_uuid()::text` is built into Postgres 13+ and works on the
 * `postgres:17-alpine` sidecar without any extension.
 *
 * Failure policy: a seed error never blocks startup — the entrypoint
 * already wraps this in `|| echo "[entrypoint] seed failed (continuing)"`.
 */
const { Pool } = require('pg');

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error('DATABASE_URL is required to run the seed.');
  }
  const login = (process.env.SEED_GITHUB_LOGIN || '').trim();
  if (!login) {
    console.log('[seed] SEED_GITHUB_LOGIN not set — skipping.');
    return;
  }

  const pool = new Pool({ connectionString: url, max: 1 });
  try {
    const { rowCount } = await pool.query(
      `INSERT INTO allowed_users (id, github_login)
       VALUES (gen_random_uuid()::text, $1)
       ON CONFLICT (github_login) DO NOTHING`,
      [login],
    );
    if (rowCount > 0) {
      console.log(`[seed] inserted '${login}' into allowed_users.`);
    } else {
      console.log(`[seed] allowlist already contains '${login}' — no-op.`);
    }
  } finally {
    await pool.end();
  }
}

main().catch((err) => {
  console.error('[seed] failed:', err && err.message ? err.message : err);
  // Never block startup on a seed failure.
  process.exit(0);
});
